<?php
    $title = 'Dashboard';
    $this->headTitle($title);
/** @var  $dashboardData \Application\DataObjects\DashboardData */
$dashboardData = $dashboardData; //cleanfix easier to code

echo '<h1>' . $this->escapeHtml($title) . '</h1>';

echo $this->dashboardHelper()->getStyle();

$uc = count($dashboardData->getActiveUsers());
$inside = " <p>All clicks:  564</p>
            <p>clicks:  564</p>
            <p>Active Users: $uc </p>";

echo $this->dashboardHelper()->wrapInBox($inside, 'User Statistics', 'left');

echo $this->dashboardHelper()->render($dashboardData->getActionLog());

?>

<box class = "dashboard dashboard-left">
    <boxtitel>
        <span class="own_text_small">System Log</span>
    </boxtitel>
    <boxcontent>
        <ul class="dash-list">
            <li>dsa</li>
            <li>dsa</li>
            <li>gfd</li>
            <li>jhgjgh</li>
        </ul>
    </boxcontent>
</box>

<?php
echo $this->dashboardHelper()->render($dashboardData->getActiveUsers());

echo $this->dashboardHelper()->getJS(); ?>