<?php
    $title = 'Dashboard';
    $this->headTitle($title);

echo '<h1>' . $this->escapeHtml($title) . '</h1>';
?>
<style>
    @keyframes newOne {
        from {
            box-shadow: inset 0px 0px 2vw 0px rgba(16, 120, 0, 0.65);
        }
        to {
            box-shadow: inset 0px 0px 2vw 0px rgba(41, 0, 0, 0.5);
        }
    }
    .dashboard
    {
        text-shadow: none;
    }

    .dashboard-left
    {
        float: left;
        width: 27%;
    }
    .dashboard-right
    {
        float: right;
        width: 67%;
    }
    .dash-list {
        max-height: 200px;
        overflow-y: auto;
        list-style-type: none
    }
    boxcontent ul {
        list-style: none;
    }
    .dash-list li {
        animation-name: newOne;
        animation-duration: 4s;
        box-shadow: inset 0px 0px 2vw 0px rgba(41, 0, 0, 0.5);
    }
    .dashboard
    {
        width: 100%;
        margin-right: 0;
        float: none !important;
    }
    @media screen and (max-width: 1350px){
        .dashboard
        {
            width: 100%;
            margin-right: 0;
            float: none !important;
        }
        .dashboard *
        {
        //font-family: normal;
            font-size: 1.5vw !important;
        }

        .dash-list li {
            box-shadow: inset 0px 0px 2vw 0px rgba(41, 0, 0, 0.5);
        }
    }
    @media screen and (max-width: 800px){
        .dashboard
        {
            width: 100%;
            margin-right: 0;
        }
        .dashboard *
        {
            font-family: normal;
            font-size: 3vw !important;
        }

        .dash-list li {
            box-shadow: inset 0px 0px 2vw 0px rgba(41, 0, 0, 0.5);
        }
    }
</style>

<?php

// ************************************************************************************* QUICK LINKS
$li = '';
if($quickLinks !== null)
    foreach ($quickLinks as $item) $li .= "<li>" . $item['string'] . "</li>";
?>
<box class = 'dashboard dashboard-left'>
    <boxtitel>
        <span class='own_text_small'>Quick Links</span>
    </boxtitel>
    <boxcontent><ul class="dash-list"><?php echo $li ?></ul></boxcontent>
</box>

<?php
// ************************************************************************************* USER STATS
$li = '';
if($userStats !== null)
foreach ($userStats as $item) $li .= "<li>" . $item['string'] . "</li>";
?>
<box class = 'dashboard dashboard-left'>
    <boxtitel>
        <span class='own_text_small'>User Statistics</span>
    </boxtitel>
    <boxcontent><ul class="dash-list"><?php echo $li ?></ul></boxcontent>
</box>

<?php
// ************************************************************************************* LIVE CLICKS
$li = '';
if($liveClicks !== null)
    foreach ( $liveClicks as $item )
        if($item !== null){
            $liCss = 'class="entry basicdata" data-timestamp="' . $item['time'] . '"';
            $li .= "<li $liCss>" . $item['string'] . "</li>";
        }
?>
<box class = 'dashboard dashboard-right'>
    <boxtitel>
        <span class='own_text_small'>Live Clicks</span>
    </boxtitel>
    <boxcontent><ul id="dashLiveList" class="dash-list"><?php echo $li ?></ul></boxcontent>
</box>

<?php
// ************************************************************************************* ACTIVE USERS
$li = '';
if($activeUsers !== null)
    foreach ( $activeUsers as $item )
        if($item !== null)
            $li .= '<li>' . $item['string'] . '</li>';
?>
<box class = 'dashboard dashboard-left'>
    <boxtitel>
        <span class='own_text_small'>Active Users</span>
    </boxtitel>
    <boxcontent><ul class="dash-list"><?php echo $li ?></ul></boxcontent>
</box>

<?php
// ************************************************************************************* SYSTEM LOG
$li = '';
if($sysLog !== null)
    foreach ( $sysLog as $item )
        if($item !== null)
            $li .= '<li>' . $item['string'] . '</li>';
?>
<box class = 'dashboard dashboard-right'>
    <boxtitel>
        <span class='own_text_small'>System Log</span>
    </boxtitel>
    <boxcontent><ul class="dash-list"><?php echo $li ?></ul></boxcontent>
</box>

<script type="text/javascript">
    //script for live ticks
    function loadLive(e) {

        e.fail(function(jqXHR, textStatus, errorThrown) {
            console.log(jqXHR, textStatus, errorThrown);
        });
        e.done(function(e, textStatus, jqXHR) {
            let actions = e.actions;
            if (actions !== null) {;
                actions.reverse();

                for (let i = 0; i < actions.length; i++) {
//                                    let DateStamp = new Date(actions[i].time)
//                                    let Hours = "0" + DateStamp.getHours();
//                                    let Minutes = "0" + DateStamp.getMinutes();
//                                    let actionsTime = Hours.substr(-2) + ':' + Minutes.substr(-2);
                    $('#dashLiveList').prepend("<li class='entry' data-timestamp='" + actions[i].time + "'>" +
                        actions[i].string + "</li>");
                }
            }
            setTimeout(function() {
                let ele =  $('#dashLiveList li:nth-child(1)');
                let since = ele.data('timestamp');
                livereload(since);
            }, 4500);
        });
    }
    function livereload(since) {
        let data = {
            method: "getLiveActions",
            since: since,
        };
        $.ajax({
            url: "/system/json",
            type: "POST",
            data: JSON.stringify(data),
            complete: loadLive
        });
    }
    livereload($('#dashLiveList li:nth-child(1)').data('timestamp'));
</script>
