<?php
    $title = 'Dashboard';
    $this->headTitle($title);
/** @var  $dashboardData \Application\DataObjects\DashboardData */
$dashboardData = $dashboardData; //cleanfix easier to code

echo '<h1>' . $this->escapeHtml($title) . '</h1>';

echo $this->dashboardHelper()->getStyle();

$inside = " <p>All clicks:  564</p>
            <p>clicks:  564</p>
            <p>Active Users: $activeUserCount </p>";
echo $this->dashboardHelper()->wrapInBox($inside, 'User Statistics', 'left');

echo $this->dashboardHelper()->render($dashboardData->getActionLog());

$inside = "<ul class='dash-list'>
                <li>not</li>
                <li>done</li>
                <li>yet</li>
                <li>sorry!!!!</li>
            </ul>";
echo $this->dashboardHelper()->wrapInBox($inside, 'System Log not implemented yet', 'left');

echo $this->dashboardHelper()->render($dashboardData->getActiveUsers());

echo $this->dashboardHelper()->getJS();