<style type="text/css">
    .fm-modal {
        z-index: 10011; /** Because CKEditor image dialog was at 10010 */
        width:80%;
        height:80%;
        top: 10%;
        left:10%;
        border:0;
        position:fixed;
        -moz-box-shadow: 0px 1px 5px 0px #656565;
        -webkit-box-shadow: 0px 1px 5px 0px #656565;
        -o-box-shadow: 0px 1px 5px 0px #656565;
        box-shadow: 0px 1px 5px 0px #656565;
        filter:progid:DXImageTransform.Microsoft.Shadow(color=#656565, Direction=180, Strength=5);
    }
</style>

<h1>Edit Template</h1>
<div id="page-edit">
    <?php $this->headScript()->appendFile('/libs/ckeditor/ckeditor.js'); ?>
    <br/><br/>
    <p class="own_text_small">
        <?php echo $form->get('name')->getValue()?>
    </p>
    <?php
    echo $this->form($form);
    echo $back;
    ?>
    <br/><br/>
    <p class="own-text-small">
        <?php
        $text = 'Mögliche Variablen: ';
        $var = $form->get('variables')->getValue();
        $varParts = explode(", ",$var);
        foreach ($varParts as $var)
            $text .= '<b> {{' . $var . '}} </b>' ;
        echo $text;
        ?>
    </p>
</div>
<script>
    $($('#page-edit textarea')[0]).attr("id","editor");
    CKEDITOR.replace( 'editor',{
    });
</script>

