<style>
    div.charprofile.familyimages,
    div.charprofile.headimages {
        float: right;
        position: relative;
        /*display: inline;*/
        margin-left: 5px;
        width: 40%;
    }
    div.charprofile.headimages.headblazon{
        float: left;
    }
    .charprofile.familyimages .blazon,
    .charprofile.headimages .blazon
    {
        width: 100px
    }
    box.familyMember
    {
        display: inline-block;
        margin-top: 0;
        margin-bottom: 5px;
        margin-right: 5px;
        width: 40%;
    }

    /*
    blazon settings in _blazons.less
    */
</style>

<?php

/** @var \Cast\View\Helper\BlazonHelper $bh */
$bh = $this->blazon();
$char['bhArg'] = $bh->getBlazonHelperArgumentsByCharacter($char);
$title = $char['name'] . ' ' . $char['surename'];
$this->headTitle($title);
$img = (isset($char['userData']->user_image)) ? $char['userData']->user_image : false;
////@todo resize
//if($img)
//{
//    list($width, $height) = getimagesize($img);
//    if ($width > $height) {
        $css = 'width: 200px';
//    } else {
//        $css = 'height: 200px';
//    }
//}


?>

    <?php echo '<div class="charprofile headimages headblazon">' . $bh->blazon($char['bhArg']) . '</div>' ?>
    <div class="charprofile headimages">
        <?php echo ($char['userData']->user_image) ? '<img style="float: right;'. $css .'" src="'. $img .'">' : 'Bild nicht gefunden' ?>
    </div>
<div class="clear"></div>
<h1>
    <span class="own_text_medium"><?php echo $this->escapeHtml($title);?></span>
</h1>
<br/>
<br/>
<box class="public-char-profile">
    <boxtitle>
    </boxtitle>
    <boxcontent>
        <h1><span class="own_text_small">Vita</span></h1><br/>
        <p><?php echo (isset($char['vita'])) ? $char['vita'] :  'vita nicht gefunden'?></p>
        <?php if ($hasFamily):
            echo '<br/><h1><span class="own_text_small">Familie</span></h1><br/>';
            foreach ($charFamily as $member): ?>
                <a href="/profile/<?php echo $member['userName'] . '/' . $member['charURL'] ?>">
                    <box class = "familyMember">
                        <boxtitle>
                            <span><?php
                                echo $member['name'] . ' ';
                                echo ( isset( $member['surename'] ) )? $member['surename'] : ''
                            ?></span>
                            <?php echo '<div class="charprofile familyimages">' . $bh->blazon() . '</div>' ?>
                        </boxtitle>
                        <boxcontent>
                            <div>
                            </div>
                        </boxcontent>
                    </box>
                </a>
            <?php endforeach;
        endif; ?>
    </boxcontent>
</box>
<div class="clear"></div>
<a href="/profile/<?php echo $username ?>">
    <button><?php echo $username ?></button>
</a>
<a href="/cast">
    <button>Tree view</button>
</a>
