<style>
    .charprofile.headimages {
        float: right;
        margin-left: 15%;
        width: 100px;
    }
    .charprofile.headimages .blazon
    {
        width: 100px
    }
    box.familyMember
    {
        margin-top: 0;
        margin-bottom: 3px;
    }
</style>

<?php
// $char = character array
//$char = $char;
//cleanfix dummy
//bdump($char);
//bdump($hasFamily);

/** @var \Cast\View\BlazonHelper $bh */
$bh = $this->blazon();

$title = $char['name'] . ' ' . $char['surename'];
$this->headTitle($title);
?>

<h1>
    <span class="own_text_medium"><?php echo $this->escapeHtml($title);?></span>
    <?php echo '<div class="charprofile headimages">' . $bh->blazon() . '</div>' ?>
    <div class="charprofile headimages">
        <?php echo (isset($char['pic'])) ? '<img style="float: right;" src="">' : 'bild nicht gefunden' ?>
    </div>
</h1>
<br/>
<br/>
<box class="public-char-profile">
    <boxtitle>
    </boxtitle>
    <boxcontent>
        <p><?php echo (isset($char['vita'])) ? $char['vita'] :  'vita'?></p>
        <?php if ($hasFamily):
            echo '<br/><h1><span class="own_text_small">Familie</span></h1><br/>';
            foreach ($charFamily as $member): ?>
                <a href="/profile/<?php echo $member['userName'] . '/' . $member['charURL'] ?>">
                    <box class = "familyMember">
                        <boxtitle>
                            <span><?php echo $member['name'] ?></span>
                        </boxtitle>
                        <boxcontent>
                            <div>info + links</div>
                        </boxcontent>
                    </box>
                </a>
            <?php endforeach;
        endif; ?>
    </boxcontent>
</box>
<a href="/profile/<?php echo $username ?>">
    <button><?php echo $username ?></button>
</a>
<a href="/cast">
    <button>Tree view</button>
</a>
