<?php
$this->headTitle($family['name']);
?>
<h1><?php echo $this->escapeHtml($family['name']); ?></h1>
<?php
$head = array();
foreach ($members as $member) {
    $head = $member;
    break;
}
echo $this->blazon()->getSingleBlazonByName($this->blazon()->getBlazonHelperArgumentsByCharacter($head), 'big');
foreach ($members as $member) {
    echo '<a href="' .$member['charProfileURL']. '"><button>';
    echo $member['name'];
    echo $this->blazon()->getSingleBlazonByName($this->blazon()->getBlazonHelperArgumentsByCharacter($member));
    echo '</button></a><br/>';
}