<?php
$title = 'Private Character Profile';
$this->headTitle($title);

bdump($char);
bdump($hasFamily);
bdump($charFamily);
bdump($username);
bdump($charnameURL);
?>
<style>
</style>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h1><span class="own_text_small"><?php echo $char['name'] . ' ' . $char['surename'] ?></span></h1>
<?php
echo $this->form($form);
echo "<a href='/profile/$username/$charnameURL'><button>Ansehen</button></a>";
?>
