

<?php
// module/MemberManager/view/album/album/index.phtml:

$title = 'Gallerie ';
$this->headTitle($title);
//dump($albums);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album/add');?>"><butti>Add new album</butti></a>
 </p>
 <table class="table" style="width: 95%;">
 <tr>
     <th style="text-align: left;">Event</th>
     <th style="text-align: right;">Datum</th>
     <th style="text-align: left;"></th>
     <th style="text-align: left;">Sichtbar</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td style="text-align: left;"><?php echo $album['event'];?></td>
     <td style="text-align: right;"><?php echo date ('d.m.', $album['timestamp']);?></td>
     <td style="text-align: left;"><?php echo date ('Y', $album['timestamp']);?></td>
     <th style="text-align: left;"><?php
         if ($album['visibility'] == 1){$visibility = 'Ja';}
         else {$visibility = 'nein';}
         echo $visibility;?></th>
     <td>
         <a href="<?php echo $this->url('album/edit', array('id' => $album['id']));?>"><butti>Edit</butti></a>
         <a href="<?php echo $this->url('album/delete', array('id' => $album['id']));?>"><butti>Delete</butti></a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
