<style>
 .user-pic
 {
  height: 200px;
  position: absolute;
  top: 0;
  right: 0;
 }
</style>
<?php
$title = 'Edit User';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('user/edit', array('id' => $this->id)));
 $form->prepare();

 echo $this->form($form);
?>

<img class="user-pic" src="<?php echo $user->user_image ?>" alt="profile pic">
