<style>
 .user-pic
 {
  height: 200px;
  position: absolute;
  top: 0;
  right: 0;
 }
 .profile-pic{
     height: 300px;
     position: absolute;
     left: 50%;
     top: 20%;
 }
</style>
<?php
$title = 'Edit User';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('user/edit', array('id' => $this->id)));
 $form->prepare();

 echo $this->form($form);

 if (isset($user->user_image) || $user->user_image !== null):
?>
<img class="profile-pic" src="<?php echo $this->media()->getImageUrl($user->user_image) ?>" alt="ProfilePic">

<?php endif;?>