<?php
$title = 'Users';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('user/add');?>">Add new User</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>eMail</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($users as $user) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($user->name);?></td>
     <td><?php echo $this->escapeHtml($user->email);?></td>
     <td>
         <a href="<?php echo $this->url('user/edit', array('id' => $user->id));?>">Edit</a>
         <a href="<?php echo $this->url('user/delete', array('id' => $user->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>