<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Nav\Module'                        => __DIR__ . '/module.php',
    'Nav\Controller\NavController'      => __DIR__ . '/src/Nav/Controller/NavController.php',
    'Nav\Factory\MainNavigationFactory' => __DIR__ . '/src/Nav/Factory/MainNavigationFactory.php',
    'Nav\Form\NavForm'                  => __DIR__ . '/src/Nav/Form/NavForm.php',
    'Nav\Model\NavTable'                => __DIR__ . '/src/Nav/Model/NavTable.php',
);
