<style>

    div.float-left
    {
        float: left;
        width: 30%;
    }
    div.float-left img
    {
        height: 150px;
    }
</style>
<?php
$title = 'Edit Family';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="float-left">
<?php
    /** @var \Zend\Form\View\Helper\Form $form */
    $form = $this->form;
    $form->prepare();
    echo $this->form($form);
?>
</div>
<div class="float-left">
<?php
    if ( $data['blazon']['filename'] ):
        $srcBlazon = $filePath . $data['blazon']['filename'];
?>
    <img alt="blazon" src="<?php echo $srcBlazon ?>">
<?php endif; ?>
</div>
<div class="float-left">
<?php
    if ( $data['blazon']['bigFilename'] ):
        $srcBlazonBig = $filePath . $data['blazon']['bigFilename'];
?>
    <img alt="blazon" src="<?php echo $srcBlazonBig ?>">
<?php endif; ?>
</div>

