<?php
$title = 'Gallerie ';
$this->headTitle($title);
//dumpd($albums);
?>

<table class="table" style="width: 95%;">
 <tr>
     <th style="text-align: left;">Jahr</th>
     <th style="text-align: left;">Event</th>
     <th style="text-align: left;">Datum</th>
     <th style="text-align: left;">&nbsp;</th>
     <th style="width: 25%;text-align: left;">&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) :
     $pre_path = '/media/image/gallery/';
     if ($album['visibility'] !== "1") {continue;}
     $prev_src = 
         ($album['preview_pic'] == NULL) ? $pre_path.'default/default.png' : $pre_path.$album['folder'].'/'.$album['preview_pic']; 
 ?>
 <tr>
     <td><?php echo date ('Y', $album['timestamp']); ?></td>
     <td><?php echo $album['event']; ?></td>
     <td><?php echo date ('d.m.Y', $album['timestamp']); ?></td>
     <td style="text-align: center"><img class = "preview_gallery" src="<?php echo $prev_src;?>"></td>
     <td>
         <a href="<?php echo $this->url('gallery/small', array('id' => $album['id']));?>"><butti>Ansehen</butti></a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
