<?php
$title = 'Gallerie ';
$this->headTitle($title);
?>

<table class="table">
 <tr>
     <th>Jahr</th>
     <th>Event</th>
     <th>Datum</th>
     <th>Dauer</th>
     <th>&nbsp;</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo "" ?></td>
     <td></td>
     <td></td>
     <td></td>
     <td><img class = "preview_gallery" src="/data/gallery/2016/t1.jpg"></td>
     <td>
         <a href="<?php echo $this->url('gallery/fullscreen', array('id' => $album->id)); ?>"><butti>Vollbild</butti></a>
         <a href="<?php echo $this->url('gallery/small', array('id' => $album->id));?>"><butti>Ansehen</butti></a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
