<?php
$this->headLink()->prependStylesheet('/libs/jgallery/css/font-awesome.min.css');
$this->headLink()->prependStylesheet('/libs/jgallery/css/jgallery.min.css');
$this->headScript()->appendFile('/libs/jgallery/js/tinycolor-0.9.16.min.js');
$this->headScript()->appendFile('/libs/jgallery/js/jgallery.min.js');
?>
<script type="text/javascript">
    $(document).ready(function() {
        $( '#gallery' ).jGallery( {
            'mode': 'standard',
            'autostart': true,
            'canClose': false,
            'backgroundColor': '#AFA08D',
            'textColor': '#000',
        });
    } );
</script>
<div id="gallery">
    <div class="album" data-jgallery-album-title="Album 1">
        <h1><?php echo $album->getName()?></h1>
        <?php foreach ($album as $image) : ?>
            <a href="<?= $src = "/media/image/".$image->path?>"><img src="<?= $src ?>" alt="Source: schwarze-ritter-augsburg.com/"  /></a>
        <?php endforeach; ?>
    </div>
</div>