<?php
$this->headLink()->prependStylesheet('/libs/jgallery/css/font-awesome.min.css');
$this->headLink()->prependStylesheet('/libs/jgallery/css/jgallery.min.css');
$this->headScript()->appendFile('/libs/jgallery/js/tinycolor-0.9.16.min.js');
$this->headScript()->appendFile('/libs/jgallery/js/jgallery.min.js');
?>
<script type="text/javascript">
    $(document).ready(function() {
        $( '#gallery' ).jGallery( {
            'mode': 'standard',
            'autostart': true,
            'canClose': false
        });
    } );
</script>
<div id="gallery">
    <div class="album" data-jgallery-album-title="Album 1">
        <h1>Album 1</h1>
        <?php foreach ($images as $image) : ?>
            <a href="<?= $src = "/media/image/gallery/".$album['folder']."/".$image['filename'].'.'.$image['extension']?>"><img src="<?= $src ?>" alt="Source: schwarze-ritter-augsburg.com/" data-jgallery-bg-color="#03040A" data-jgallery-text-color="#F1A8FF" /></a>
        <?php endforeach; ?>
    </div>
</div>
