<?php
$title = 'Roles';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('role', array('action'=>'add'));?>">Add new Role</a>
 </p><pre>
<?php var_dump($roles); ?>
</pre>
 <table class="table">
 <tr>
     <th>Name</th>
     <th>Parent</th>
     <th>Status</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($roles as $role) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($role['role_name']);?></td>
     <td><?php echo $this->escapeHtml($role['role_parent_name']);?></td>
     <td><?php echo $this->escapeHtml($role['status']);?></td>
     <td>
         <a href="<?php echo $this->url('role',
             array('action'=>'edit', 'id' => $role['id']));?>">Edit</a>
         <a href="<?php echo $this->url('user',
             array('action'=>'delete', 'id' => $role['id']));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>