<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Gallery\Module'                           => __DIR__ . '/Module.php',
    'Gallery\Controller\GalleryController'     => __DIR__ . '/src/Gallery/Controller/GalleryController.php',
    'Gallery\Factory\GalleryControllerFactory' => __DIR__ . '/src/Gallery/Factory/GalleryControllerFactory.php',
    'Gallery\Factory\GalleryServiceFactory'    => __DIR__ . '/src/Gallery/Factory/GalleryServiceFactory.php',
    'Gallery\Factory\RandomImageHelperFactory' => __DIR__ . '/src/Gallery/Factory/RandomImageHelperFactory.php',
    'Gallery\Form\AlbumForm'                   => __DIR__ . '/src/Gallery/Form/AlbumForm.php',
    'Gallery\Form\ConfirmForm'                 => __DIR__ . '/src/Gallery/Form/ConfirmForm.php',
    'Gallery\Form\Filter\AlbumFilter'          => __DIR__ . '/src/Gallery/Form/Filter/AlbumFilter.php',
    'Gallery\Form\Filter\ImageFilter'          => __DIR__ . '/src/Gallery/Form/Filter/ImageFilter.php',
    'Gallery\Form\ImageForm'                   => __DIR__ . '/src/Gallery/Form/ImageForm.php',
    'Gallery\Model\AlbumModel'                 => __DIR__ . '/src/Gallery/Model/AlbumModel.php',
    'Gallery\Service\GalleryService'           => __DIR__ . '/src/Gallery/Service/GalleryService.php',
    'Gallery\Utility\RandomImageHelper'        => __DIR__ . '/src/Gallery/View/Helper/RandomImageHelper.php',
);
