<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cms\Module'                           => __DIR__ . '/Module.php',
    'Cms\Controller\ContentController'     => __DIR__ . '/src/Cms/Controller/ContentController.php',
    'Cms\Controller\PageController'        => __DIR__ . '/src/Cms/Controller/PageController.php',
    'Cms\Factory\ContentControllerFactory' => __DIR__ . '/src/Cms/Factory/ContentControllerFactory.php',
    'Cms\Factory\PageControllerFactory'    => __DIR__ . '/src/Cms/Factory/PageControllerFactory.php',
    'Cms\Factory\PostServiceFactory'       => __DIR__ . '/src/Cms/Factory/PostServiceFactory.php',
    'Cms\Factory\ZendDbSqlMapperFactory'   => __DIR__ . '/src/Cms/Factory/ZendDbSqlMapperFactory.php',
    'Cms\Form\PostFieldset'                => __DIR__ . '/src/Cms/Form/PostFieldset.php',
    'Cms\Form\PostForm'                    => __DIR__ . '/src/Cms/Form/PostForm.php',
    'Cms\Mapper\PostMapperInterface'       => __DIR__ . '/src/Cms/Mapper/PostMapperInterface.php',
    'Cms\Mapper\ZendDbSqlMapper'           => __DIR__ . '/src/Cms/Mapper/ZendDbSqlMapper.php',
    'Cms\Model\Post'                       => __DIR__ . '/src/Cms/Model/Post.php',
    'Cms\Model\PostInterface'              => __DIR__ . '/src/Cms/Model/PostInterface.php',
    'Cms\Service\PostService'              => __DIR__ . '/src/Cms/Service/PostService.php',
    'Cms\Service\PostServiceInterface'     => __DIR__ . '/src/Cms/Service/PostServiceInterface.php',
);
