<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cms\Module'                                      => __DIR__ . '/Module.php',
    'Cms\Controller\ContentController'                => __DIR__ . '/src/Cms/Controller/ContentController.php',
    'Cms\Controller\PageController'                   => __DIR__ . '/src/Cms/Controller/PageController.php',
    'Cms\Factory\Controller\ContentControllerFactory' => __DIR__ . '/src/Cms/Factory/Controller/ContentControllerFactory.php',
    'Cms\Factory\Controller\PageControllerFactory'    => __DIR__ . '/src/Cms/Factory/Controller/PageControllerFactory.php',
    'Cms\Factory\Service\ContentServiceFactory'       => __DIR__ . '/src/Cms/Factory/Service/ContentServiceFactory.php',
    'Cms\Form\ContentFieldSet'                        => __DIR__ . '/src/Cms/Form/ContentFieldSet.php',
    'Cms\Form\ContentForm'                            => __DIR__ . '/src/Cms/Form/ContentForm.php',
    'Cms\Model\DataModels\Content'                    => __DIR__ . '/src/Cms/Model/DataModels/Content.php',
    'Cms\Model\ContentTable'                          => __DIR__ . '/src/Cms/Model/Tables/ContentTable.php',
    'Cms\Service\ContentService'                      => __DIR__ . '/src/Cms/Service/ContentService.php',
);
