<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Media\Module'                           => __DIR__ . '/Module.php',
    'Media\Controller\FileBrowserController' => __DIR__ . '/src/Media/Controller/FileBrowserController.php',
    'Media\Controller\FileController'        => __DIR__ . '/src/Media/Controller/FileController.php',
    'Media\Controller\ListController'        => __DIR__ . '/src/Media/Controller/ListController.php',
    'Nav\Factory\FileControllerFactory'      => __DIR__ . '/src/Media/Factory/FileControllerFactory.php',
    'Media\Factory\GeneralMediaFactory'      => __DIR__ . '/src/Media/Factory/GeneralMediaFactory.php',
    'Media\Factory\MediaServiceFactory'      => __DIR__ . '/src/Media/Factory/MediaServiceFactory.php',
    'Media\Model\FileTable'                  => __DIR__ . '/src/Media/Model/FileTable.php',
    'Media\Service\ERROR_TYPES'              => __DIR__ . '/src/Media/Service/ERROR_TYPES.php',
    'Media\Service\MediaException'           => __DIR__ . '/src/Media/Service/MediaException.php',
    'Media\Service\MediaItem'                => __DIR__ . '/src/Media/Service/MediaItem.php',
    'Media\Service\MediaService'             => __DIR__ . '/src/Media/Service/MediaService.php',
    'Media\Utility\BaseUploadHandler'        => __DIR__ . '/src/Media/Utility/BaseUploadHandler.php',
    'Media\Utility\FmHelper'                 => __DIR__ . '/src/Media/Utility/FmHelper.php',
    'Media\Utility\LocalUploadHandler'       => __DIR__ . '/src/Media/Utility/LocalUploadHandler.php',
);
