<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Media\Module'                           => __DIR__ . '/Module.php',
    'Media\Controller\FileBrowserController' => __DIR__ . '/src/Media/Controller/FileBrowserController.php',
    'Media\Controller\FileController'        => __DIR__ . '/src/Media/Controller/FileController.php',
    'Media\Controller\ListController'        => __DIR__ . '/src/Media/Controller/ListController.php',
    'Media\Controller\UploadController'      => __DIR__ . '/src/Media/Controller/UploadController.php',
    'Media\Model\FileTable'                  => __DIR__ . '/src/Media/Model/FileTable.php',
    'Media\Service\ERROR_TYPES'              => __DIR__ . '/src/Media/Service/MediaService.php',
    'MediaItem'                              => __DIR__ . '/src/Media/Service/MediaService.php',
    'MediaException'                         => __DIR__ . '/src/Media/Service/MediaService.php',
    'MediaService'                           => __DIR__ . '/src/Media/Service/MediaService.php',
    'Media\Utility\BaseUploadHandler'        => __DIR__ . '/src/Media/Utility/BaseUploadHandler.php',
    'Media\Utility\FmHelper'                 => __DIR__ . '/src/Media/Utility/FmHelper.php',
    'Media\Utility\LocalUploadHandler'       => __DIR__ . '/src/Media/Utility/LocalUploadHandler.php',
);
