<?php

$title = 'Add Menu Item';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('nav/add'));
 $form->prepare();
 
 echo $this->form($form);
//  echo $this->form()->openTag($form);
//  echo $this->formHidden($form->get('id'));
//  echo $this->formRow($form->get('title'));
//  echo $this->formRow($form->get('artist'));
//  echo $this->formSubmit($form->get('submit'));
//  echo $this->form()->closeTag();
