<?php
$title = 'Edit Menu';
// $this->headLink()->prependStylesheet('/libs/jstree/themes/default-dark/style.css');
$this->headScript()->appendFile('/js/selectedUsage/jquery/nestable/jquery.nestable.js');
// $this->headScript()->appendFile('/libs/jstree/jstree.min.js');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<input id="save-menu" type="button" value="Save Sorting">
<input id="add-menu-item" type="button" value="Add Item">
<div id="navTree" class="dd">
    <br>
    <?php echo $this->render('navTreeEdit.phtml'); ?>
</div>
<div style="clear: both"></div>


<script type="text/javascript">

    $(document).ready(function(){
    	$('.dd').nestable({});

        $('#save-menu').on('click', function() {
        	var data = $('.dd').nestable('serialize');
        	data = JSON.stringify(data);
        	console.log(data);
            $.ajax
            ({
                type: "POST",
                url: '/nav/sort',
                dataType: 'json',
                async: true,
                data: data,
                success: function (e, a) {
					console.log(e, a);
                    feedback.success('Neue Sortierung gespeichert, oder hast du etwas anderes erwartet?');
                },
                error: function (e, a) {
    				console.log(e.responseText, a);
                    feedback.error('Fehler, bitte hauen Sie ihren Kopf gegen die Wand^^');
                }
            }).done(function( msg ) {
                console.log(msg);
            });
        });
        $('#add-menu-item').on('click', function() {
        	var getUrl = window.location;
        	var url = getUrl.protocol + "//" + getUrl.host + "/nav/add";
        	window.location = url;
        });
        $('.dd-edit').on('click', function(e) {
        	$(this).parent('.dd3-content').toggleClass('dd-expanded');
            //console.log($(this).parent('.dd3-content') );
        });
        $('.dd-delete').on('click', function(e) {
            var $parent = $(this).parent('.dd3-content');
            var id = $(".dd-details>form>input[name=id]", $parent).val();
            var getUrl = window.location;
            var url = getUrl.protocol + "//" + getUrl.host + "/nav/delete/"+ id;
            window.location = url;
        });
    });
</script>








