<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Calendar\Module'                                       => __DIR__ . '/Module.php',
    'Calendar\Controller\CalendarController'                => __DIR__ . '/src/Calendar/Controller/CalendarController.php',
    'Calendar\Factory\Controller\CalendarControllerFactory' => __DIR__ . '/src/Calendar/Factory/Controller/CalendarControllerFactory.php',
    'Calendar\Factory\Helper\UpcomingEventsFactory'         => __DIR__ . '/src/Calendar/Factory/Helper/UpcomingEventsFactory.php',
    'Calendar\Factory\Service\CalendarServiceFactory'       => __DIR__ . '/src/Calendar/Factory/Service/CalendarServiceFactory.php',
    'Calendar\Form\CalendarForm'                            => __DIR__ . '/src/Calendar/Form/CalendarForm.php',
    'Calendar\Form\EventForm'                               => __DIR__ . '/src/Calendar/Form/EventForm.php',
    'Calendar\Form\UpdateTokenForm'                         => __DIR__ . '/src/Calendar/Form/UpdateTokenForm.php',
    'Calendar\Service\CalendarService'                      => __DIR__ . '/src/Calendar/Service/CalendarService.php',
    'Calendar\View\Helper\UpcomingEvents'                   => __DIR__ . '/src/Calendar/View/Helper/UpcomingEvents.php',
);
