<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Calendar\Module'                        => __DIR__ . '/Module.php',
    'Calendar\Controller\CalendarController' => __DIR__ . '/src/Calendar/Controller/CalendarController.php',
    'Calendar\Form\CalendarForm'             => __DIR__ . '/src/Calendar/Form/CalendarForm.php',
    'Calendar\Form\EventForm'                => __DIR__ . '/src/Calendar/Form/EventForm.php',
    'Calendar\Service\CalendarService'       => __DIR__ . '/src/Calendar/Service/CalendarService.php',
    'Auth\View\Helper\GoogelCalendarView'    => __DIR__ . '/src/Calendar/View/Helper/GoogleCalendarView.php',
    'Calendar\View\Helper\UpcomingEvents'    => __DIR__ . '/src/Calendar/View/Helper/UpcomingEvents.php',
);
