<?php
$title = $page['label'];
$this->headTitle($title);
if (isset($links)){
    foreach ($links as $key => $value): ?>
        <a href="<?php echo $value ?>">
            <button><?php echo $key ?></button>
        </a>
    <?php endforeach;
    echo '<br/>';
    echo '<br/>';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Sicher, dass das  <?php echo bdump($equip->name); ?> gelöscht werden soll?</p>

<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $equip->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>