<?php
$title = 'delete';
$this->headTitle($title);
if (isset($links)){
    foreach ($links as $link) {
        echo '<a href="' . $link['url'] . '"><button>' . $link['name'] . '</button></a>';
    }
    echo '<br/>';
    echo '<br/>';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Sicher, dass <?php echo $tent->readableType ?> gelöscht werden soll?</p>

<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $tent->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>