<?php
$title = $page['label'];
$this->headTitle($title);
if (isset($links)){
    foreach ($links as $key => $value): ?>
        <a href="<?php echo $value ?>">
            <button><?php echo $key ?></button>
        </a>
    <?php endforeach;
    echo '<br/>';
    echo '<br/>';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
echo '<pre>';
var_dump (get_object_vars($equip));
echo '</pre>';