<?php
$title = $page['label'];
$this->headTitle($title);
if (isset($links)){
    foreach ($links as $key => $value): ?>
        <a href="<?php echo $value ?>">
            <button><?php echo $key ?></button>
        </a>
    <?php endforeach;
    echo '<br/>';
    echo '<br/>';
}
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h1><?php echo $equip->name; ?></h1>

<?php // ================================== Images:
if ($equip->image !== null): ?>
<img alt="kein Bild hinterlegt" src="<?php echo $equip->image?>" style="float: left; height: 50px;" >
<?php endif; ?>
<?php if ($equip->image1 !== null): ?>
    <img alt="kein Bild hinterlegt" src="<?php echo $equip->image1?>" style="float: left; height: 50px;" >
<?php endif; ?>
<?php if ($equip->image2 !== null): ?>
    <img alt="kein Bild hinterlegt" src="<?php echo $equip->image1?>" style="float: left; height: 50px;" >
<?php endif; ?>
<br class="clear"/>
<?php // =================================== Details ?>
<h1>Maße:</h1>
<p><?php echo $equip->width/100?> m</p>
<p><?php echo $equip->length/100?> m</p>
<?php if ((int)$equip->itemType == \Equipment\Model\Enums\EEquipTypes::TENT): ?>
<h1>Bauart:</h1>
<p><?php echo \Equipment\Model\Enums\ETentShape::TRANSLATION[$equip->shape]?></p>
<p><?php echo \Equipment\Model\Enums\ETentType::TRANSLATE_TO_STRING[$equip->type]?></p>
<?php
if ((int)$equip->isShowTent == 1)
    echo '<h1>Schauzelt</h1>';
if (isset ($equip->spareBeds) && (int)$equip->spareBeds > 0 )
    echo "<p>Freie Schlafplätze: $equip->spareBeds</p>";

endif; ?>