<h1><?php echo $this->translate('An error occurred') ?></h1>
<h2><?php echo  $this->message ?></h2>

<?php
//test
$test = getenv('APPLICATION_ENV');
$test = 'production';
switch ($test){
// test end
//switch (getenv('APPLICATION_ENV')) {
    case ("development"):
        if (isset($this->display_exceptions) && $this->display_exceptions):
            if(isset($this->exception) && $this->exception instanceof Exception): ?>
                <hr/>
                <h2><?php echo $this->translate('Additional information') ?>:</h2>
                <h3><?php echo get_class($this->exception); ?></h3>
                <dl>
                    <dt><?php echo $this->translate('File') ?>:</dt>
                    <dd>
                        <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
                    </dd>
                    <dt><?php echo $this->translate('Message') ?>:</dt>
                    <dd>
                        <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getMessage()) ?></pre>
                    </dd>
                    <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                    <dd>
                        <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
                    </dd>
                </dl>
                <?php
                $e = $this->exception->getPrevious();
                if ($e) :
                    ?>
                    <hr/>
                    <h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
                    <ul class="unstyled">
                        <?php while($e) : ?>
                            <li>
                                <h3><?php echo get_class($e); ?></h3>
                                <dl>
                                    <dt><?php echo $this->translate('File') ?>:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                                    </dd>
                                    <dt><?php echo $this->translate('Message') ?>:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getMessage()) ?></pre>
                                    </dd>
                                    <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                                    <dd>
                                        <pre class="prettyprint linenums"><?php echo $this->escapeHtml($e->getTraceAsString()) ?></pre>
                                    </dd>
                                </dl>
                            </li>
                            <?php
                            $e = $e->getPrevious();
                        endwhile;
                        ?>
                    </ul>
                <?php endif; ?>

            <?php else: ?>

                <h3><?php echo $this->translate('No Exception available') ?></h3>

            <?php endif;
        endif;
        break;
    case('production'):
    default:  ?>
        <br/>
        <h1>Leider ist ein Fehler aufgetreten.</h1>
        <p>Unser System ist direkt mit dem Verantwortlichen verbunden.</p>
        <p>Wenn sie dies hier lesen hat er bereits einen Stromschlag bekommen,</p>
        <p>durch betätigen des Zurückknopfes bekommt er einen weiteren und Sie gelangen auf die letzte Seite zurück.</p>
        <button style="margin: 10px; height: 30px; width: 60px;" onclick="window.history.back();">Zurück</button>
    <?php
}
?>


<link href="/css/fun.css" media="screen" rel="stylesheet" type="text/css">

<div class="greentree-wrap">
    <div class="tree greentree">
        <div class="trunk">
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
            <div class="branch">
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
                <div class="leaf"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $('.greentree-wrap').prependTo('.body');
</script>