<?php
$title = 'Usermanager ';
$this->headTitle($title);
//$this->dataTable->setController($controller);
$this->dataTable();
$this->dataTable()->setAllowance($allowance);
if ($allowance !== 'editor'):
?>
<a href="<?= $this->url('/usermanager/add', array());?>">Mitglied hinzufügen</a>
<?php
    endif;

echo $this->dataTable()->render($profiles, $hidden_columns);
//den musst du jetzt erst wieder umbauen oder?nicht viel moment