<?php
$title = 'Usermanager ';
$this->headTitle($title);

$this->dataTable()->setJSOptions($jsOptions);
echo $addButton . '<br><br>';
//echo $this->dataTable()->render($profiles);




echo $this->dataTable()->render($profiles, array(
    'all' => true,
    'columns' => array(
        'Name' => 'Name',
        'eMail' => 'eMail',
        'Aktionen' => 'Aktionen'
        //example of type custom
        //'Aktionen' => array(
        //    'type' => 'custom',
        //    'render' => function($row) {
        //        return '<a href.....';
        //    }
        //)
    )
));
