<?php

$title = 'Profil';
$this->headTitle($title);
?>

<a href="/<?= $controller;?>">Zurück</a><br><br>
<?php
echo $datatableHelper->renderForm($form);
?>
<script>
 //datepicker
 $('#content input[name="date"]').datepicker({
  dateFormat: "dd.mm.yy",
  defaultDate: $.datepicker.parseDate('@', $('#content input[name="timestamp"]').val()),
  onSelect: function (selectedDate) {
   var date = new Date($('#content input[name="date"]' ).val());
   $('#content input[name="timestamp"]').val(date.getTime() / 1000);
  }
 });
</script>
