<?php

$title = 'Profil';
$this->headTitle($title);
?>

<a href="/usermanager">Zurück</a><a href="/usermanager/show/<?= $id ?>">Darstellung</a><br><br>
<?php

$this->form()->setFieldConfig($field_config);
echo $this->form()->render($form);
//fry todo pw ändern if ($owner)...
?>


<script>
 //datepicker
 $('#content input[name="birthday"]').datepicker({
  dateFormat: "dd.mm.yy",
  defaultDate: $.datepicker.parseDate('@', $('#content input[name="birthday"]').val()),
  onSelect: function (selectedDate) {
   var date = new Date($('#content input[name="birthday"]' ).val());
   $('#content input[name="timestamp"]').val(date.getTime() / 1000);
  }
 });

 var create = new Date($('#content input[name="created_on"]').val());
 var mod = new Date($('#content input[name="modyfied_on"]').val());
</script>
