<?php

$title = $event. ' löschen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
echo $this->form($form);
/*
$form->prepare();
$formContent = '';
echo $this->form()->openTag($form);
foreach ($form as $element)
{
    $formContent .= $this->formrow($element) . '<br/>';
}

$new = explode('<select ', $formContent);
$formContent = implode('<br><select ', $new);
echo $formContent;
echo $this->form()->closeTag();  */
?>

