<?php
$title = $this->translate("Calendar");
$this->headTitle($title);

$this->headLink()->prependStylesheet($this->basePath('libs/fullcalendar/fullcalendar.css'));
$this->headScript()->prependFile($this->basePath('libs/fullcalendar/fullcalendar.js'));
$this->headScript()->prependFile($this->basePath('libs/fullcalendar/lib/moment.min.js'));

$form->prepare();
?>
<style>
    .flex {
        display: flex;
        overflow: hidden;
    }
    .form {

    }
    .preview {
        width: 200px;
        transition: all 0.5s linear;
    }
    .preview .wrapper {
        width: 200px;
    }
    .preview .wrapper *
    {
        list-style: none;
    }
    .hideFlex {
        width: 0px;
        transition: all 0.5s linear;
    }
    td.fc-sun,
    td.fc-sat
    {
        background: linear-gradient(#dbd2c9, white 75%, transparent);
    }
    td.fc-mon,
    td.fc-tue,
    td.fc-wed,
    td.fc-thu,
    td.fc-fri
    {
        background: linear-gradient(#dbd2c9, white 50%, transparent);
    }

</style>
<div class="box event-details">
    <div class="flex">
        <div class="form">
            <h3>Event add/edit form</h3>
            <?php echo $this->form($form); ?>
        </div>
        <div class="preview">
            <ul class="wrapper">
                <li>
                    <h3 class="item" name="title">Event Title</h3>
                    <ul>
                        <li><p class="item" name="description">beschreibung</p></li>
                        <li><p class="item" name="date">start zeit</p></li>
                        <li><p class="item" name="time">end zeit</p></li>
                        <li><p class="item" name="allDay">allDay</p></li>
                        <li><p class="item" name="calendar_id">calendar id</p></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<div id="calendar"></div>
<?php
$this->inlineFromFile('Calendar', 'Calendar', 'calendar.js', array(
    'canEdit' => true,
));
$this->inlineFromFile('Calendar', 'Calendar', 'contextMenu.js');
?>