<?php
    $title = 'Resources';
    $this->headTitle($title);


    echo '<a href="' .  $this->url('resource', array('action'=>'add')) . '">Add new Resource</a><br><br>';

    echo $this->dataTable()->render(new \Application\Utility\DataTable ( array(
        'data' => $resources,
        'configuration' => array(
            'buttons' => array(//bis auf einen fehler^^ dass er statt {}  "{}" macht
                'pdf',
                'print',
                array(
                    'text' => 'add',
                    'url' => '/resource/add',//wo is jetzt da ne hässliche func in dem array
                )
            ),
        ),
        'columns' =>    array(
            array (
                'name'  => 'resource_name',
                'label' => 'Resource'
            ),
            array (
                'name'  => 'href',
                'label' => 'Aktion',
                'type'  => 'custom',
                'render' => function($row) {
                    $edit = '<a href="/resources/edit/'.$row['id'].'">Edit</a>';
                    $delete = '<a href="/resources/delete/'.$row['id'].'">Delete</a>';
                    return $edit.$delete;
                }
            )
        )
    )));
?>