<?php

$title = 'Neues Album';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('album', array('action' => 'add')));
 $form->prepare();
 
 
 // echo $this->formCollection($form);
  echo $this->form()->openTag($form);
  echo $this->formHidden($form->get('id'));
  echo $this->formRow($form->get('event'));
  echo '<br>';
  echo $this->formRow($form->get('date'));
  echo '<br>';
  echo $this->formRow($form->get('duration'));
  echo '<br>';
  echo $this->formRow($form->get('path'));
echo "Durchsuchen?????" // durchsuchenknopf und/oder upload???????????
  echo '<br>';
  echo $this->formSubmit($form->get('submit'));
  echo $this->form()->closeTag();
