<?php

$title = 'Add new album';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('album', array('action' => 'add')));
 $form->prepare();
 
 
 echo $this->formCollection($form);
//  echo $this->form()->openTag($form);
//  echo $this->formHidden($form->get('id'));
//  echo $this->formRow($form->get('event'));
//  echo $this->formRow($form->get('datum'));
//  echo $this->formRow($form->get('duration'));
//  echo $this->formSubmit($form->get('submit'));
//  echo $this->form()->closeTag();
