<?php

$title = 'Edit Gallery';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div><a href="/album">zurück</a><br><br></div>
<?php
echo $this->form($form);
?>
<script>
 //datepicker
 $('#content input[name="date"]').datepicker({
  dateFormat: "dd.mm.yy",
  defaultDate: $.datepicker.parseDate('@', $('#content input[name="timestamp"]').val()),
  onSelect: function (selectedDate) {
   var date = new Date($('#content input[name="date"]' ).val());
   $('#content input[name="timestamp"]').val(date.getTime() / 1000);
  }
 });
</script>
