<?php

$title = 'Edit Album';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'album',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('event'));
 echo $this->formRow($form->get('datum'));
 echo $this->formRow($form->get('duration'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
