<?php

$title = 'Edit Gallery';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->prepare();
 echo $this->form($form);
?>
<!--
<script>
    $('#content input[name="date"]').datepicker({
        dateFormat: "yy-mm-dd",
        defaultDate: $.datepicker.parseDate('@', $('#content input[name="timestamp"]').val()),
        onSelect: function (selectedDate) {
            var date = new Date($('#content input[name="date"]' ).val());
            $('#content input[name="timestamp"]').val(date.getTime());
        }
    });
</script>
-->
