<?php
// module/Album/view/album/album/index.phtml:

$title = 'Gallerie ';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('album', array('action'=>'add'));?>"><butti>Add new album</butti></a>
 </p>

 <table class="table">
 <tr>
     <th>Event</th>     <?php //@todo sort by?>
     <th>Datum</th>     <?php //@todo sort by?>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->title);?></td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
     <td>
         <a href="<?php echo $this->url('album',
             array('action'=>'show', 'id' => $album->id));?>"><butti>Ansehen</butti></a>
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $album->id));?>"><butti>Edit</butti></a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album->id));?>"><butti>Delete</butti></a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
