Hier soll dann die Gallery gestartet sein....
<br><br>


<h1>Event</h1><br>
von $date<br>
Dauer $duration Tage<br>
<br>
bilder:<br><br>
<div style="font-size: 20px; text-transform: full-width; font-family: courier;">

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@#@@WWWWWWWWWWWWW<br>

WWWWWWWWWWWWWWWWWWWWWW##@@@WWWWWW@@#@@@@@WWWWWWWWWWWWW<br>

WWWWWWWWWWWWWWWWWWWWW@#####WWWW@@###@@##@WWWWWWWWWWWWW<br>

WWWWWWWWWWWWWWWWWWWWW@W==#@WWWWW====###@WWWWWWWWWWWWWW<br>

WWWWWWWWWWWWWWWWWWWWWWW@##@WWWW@##@@@WWWWWWWWWWWWWWWWW<br>

WWWWWWWWWWWWWWWWWWWWWWWWW@=#@WW@=##@WWWWWWWWWWWWWWWWWW<br>

WWWWWWWWWWWWWWW@WWWWW@@@@@#@WWW=###@WW#WWWWWWWWWWWWWWW<br>

WWWWWWWWWWWWWW@##W=*W@@#WWWWW@#====#@###WWWWWWWWWWWWWW<br>

WWWWWWWWWWWWW@###W@@WWWW@WWW@WWWWW##=#=#@WWWWWWWWWWWWW<br>

WWWWWWWWWWWWWW#####WWWWWWWWW@@WWW@######WWWWWWWWWWWWWW<br>

WWWWWWWWWW@@@WW@@####WW@#@@@##@@WW####@WW@@@@WWWWWWWWW<br>

WWWWW@@W@@@@############=======############@@@WW@@WWWW<br>

WWWW####=##=###@@@@@W@###=====###WW@@@####=###=###@WWW<br>

WWW@#############@WW@WW==##@#==@W@@W@@###=#########WWW<br>

WWWWWW@#@@@@@@@@@@@@@W@===##===@W@@W@@@@@@@@@@##WWWWWW<br>

WWWW@@W@@@#=###@@@@@@W@=@@###@##@@@@@@W@##=##@@W@@WWWW<br>

WWWWW@@@@##@###@@WW@=====####=====#W@@@####@#@@@@W@WWW<br>

WWW@@@@@##=#@#@@@@@=#W#===###===W#=@@@@@@##=#=@@@@@WWW<br>

WWW@#@@#@##=@@#@@====================#@##@#=###@@#@@@W<br>

#==##@@W@@#@WWWWW==========@=========@WWWWW##@@@@@#==#<br>

W=###WWWWW@@@@WWW==#=##@W@WWW=#@@@===@WWW@@@@@WWW###=@<br>

W@####@WW@@###=@W==#==####@WW@#@WW#==@W####@@WW@@####W<br>

WW######@WW###=#@====#W##WWWW@@@W###=#@=##=@W@######WW<br>

WWW@###@###@@@@W@======@WWWW@@W@@#===#W@@@@###@##=#WWW<br>

WWW@#=####=###WW@======@WWW@=#@======#WW@##=#######WWW<br>

WWWWWW@WWW@@W@#@W#====@W#WWW##@#=====@W#@W@@@@WW@WWWWW<br>

WWWWWWWW@@@@WW@@W#=======@WWW@======#W@@@W@@W@WWWWWWWW<br>

WWWWWWWWWW@W@WWWWW#=====#W##W#======WWWWW@W@WW@WWWWWWW<br>

WWWWWWWWWWWW@W@WWWW@=====####=====@WWWW@WWW@W@WWWWWWWW<br>

WWWWWWWWW@WWWWWWWWWWW@#========#@WWWWWWWW@W@@@WWWWWWWW<br></div>
