<?php
$title = 'file Browser';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('cms/add');?>">Add new Content</a>
</p>
<table class="table" style="width:90%">
    <tr>
        <th>name</th>
        <th>path</th>
    </tr>
 <?php foreach ($files as $file) : ?>
     <tr>
         <td><?php echo $this->escapeHtml($file->name);?></td>
         <td><?php echo $this->escapeHtml($file->name);?></td>
     </tr>
 <?php endforeach; ?>
</table>




<div id="filebrowser">
    <div class="head-bar"></div>
    <div class="file-tree"></div>
    <div class="content"></div>
    <div class="foot-bar"></div>
</div>
<script type="text/javascript">
    window.tempFilesForFileBrowser = '<?= $jsonFiles ?>';
</script>