<?php echo $this->doctype(); ?>

<html>
<head>
    <meta charset="utf-8">
        <?php echo $this->headTitle('Schwarze Ritter zu Augsburg') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
<!--    CSS styles   -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'))
//                        ->prependStylesheet($this->basePath('css/jgallery.css'))
//                        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
//                        ->prependStylesheet($this->basePath('css/media.css'))
//                        ->prependStylesheet($this->basePath('css/menu.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
        ?>
<!--    jquery scripts   -->
    <?php echo $this->headScript()
            ->prependFile($this->basePath('js/last_fixes.js'))
            ->prependFile($this->basePath('js/popup.js'))
            ->prependFile($this->basePath('js/menu.js'))
            ->prependFile($this->basePath('js/jquery-ui.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
    ; ?>

</head>

<body>
    <noscript>
        <div>
            <ownhead>Java Script aktivieren um diese Seite zu erleben!</ownhead>
        </div>
    </noscript>
    <div id="headcontainer">
        <div id="headdeko">
            <img src="/img/Wappenklein.png">
        </div>
        <div id="head">
            <a href="<?php echo $this->url('home') ?>"><ownhead>Schwarze Ritter zu Augsburg</ownhead></a>
        </div>
        <div id="headlinks">
            <span><a href="#">Kontakt </a></span> <span class="L_spacer"> | </span>
            <span><a href="#"> Impressum</a></span> <span class="L_spacer"> | </span> <br class="M_S_br">
            <span><a class="disclaim" href="#"> Haftungsausschluss</a></span><br><br class="M_br">
            <?php $greet = $this->userinfo(); if ($greet != '') {echo $greet;} ?>
        </div>
    </div>
    <div class="bodycontainer">

        <div class="navframe">
            <div class="navbutton">
                <img class=menu_close src="/img/uikit/menu_button1.png">
                <img class="menu_open" src="/img/uikit/menu_button2.png">
            </div>
            <div class="menuItems hidden">
                <div class="navtitel">
                    <owntitel>Wegweiser</owntitel>
                    <div class="spacer_h"></div>
                </div>
                <?php echo $this->navigation('navigation')->menu()->setPartial('menu.phtml')->renderPartial(); ?>
        		<?php //echo $this->navigation('navigation')->menu(); ?>

            </div>
            <script>menuapp.organizeMenu ()</script>
        </div>

        <div id="content">
            <owntitel><?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->renderStraight();//$this->contentTitle ?></owntitel><br><div class="spacer_h"></div>

            <?php echo $this->content; ?>
        </div>

        <div class="rightcontainer">
            <div class="rightbarup">
                <owntitel>~Login~</owntitel><div class="spacer_h"></div><br>
                <?php
                    $form = new Auth\Form\LoginForm('Login');
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formCollection($form);
                    echo $this->form()->closeTag();
                ?>
            </div>

            <div class="rightbardown">
                <a href="#"><owntitel><news>~Informationen~</news></owntitel></a><div class="spacer_h"></div><br>
                <span><newstitel>24.12.0006</newstitel></span><br>
                <span>Christi Geburt, Geschenke fürs Wichteln kaufen!!!</span><br><br>
                <span><newstitel>15.03.44 BC 9:00</newstitel></span><br>
                <span>Bei Brutus die geschliffenen Messer vorbeibringen. Pünktlich sein, er hat noch einen Termin bei seinem Vater!!</span><br><br>
                <span><newstitel>333 BC</newstitel></span><br>
                <span>Schlacht bei Issos, bitte Schwert nicht vergessen</span><br><br>
        </div>

        </div>
    </div>
    <div style="clear: both"></div>
    <div id="foot">
        <div id="foottext">
            <span>copyright © 2016 Schwarze Ritter zu Augsburg</span>
        </div>
        <div id="footimage"></div>
    </div>
    <script>last_fixes.organize ()</script>
    <?php echo $this->inlineScript() ?>
    <div></div>
</body>
</html>
