<?php echo $this->doctype(); ?>
<html>
<head>
<!----  Meta & Titel   ---->
    <meta charset="utf-8">
    <?php echo $this->headTitle('Schwarze Ritter zu Augsburg');

        echo $this->headMeta()
                        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>
<!----  CSS styles & favicon  ---->
    <?php echo $this->headLink( array( 'rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico' ) )
                        ->prependStylesheet($this->basePath('libs/globalUsage/feedback/css/feedback.css'))
                        ->prependStylesheet($this->basePath('libs/globalUsage/jquery-ui/jquery-ui.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
        ?>
<!----  jquery scripts   ---->
    <?php echo $this->headScript()
                        ->prependFile($this->basePath('libs/globalUsage/feedback/js/feedback.js'))
                        ->prependFile($this->basePath('js/globalUsage/accordion/accordion.js'))
                        ->prependFile($this->basePath('js/globalUsage/logOutDesigner/logOutDesigner.js'))
                        ->prependFile($this->basePath('js/globalUsage/menu/menu.js'))
                        ->prependFile($this->basePath('js/globalUsage/popUp/popUp.js'))
                        ->prependFile($this->basePath('libs/globalUsage/jquery-ui/jquery-ui.min.js'))
                        ->prependFile($this->basePath('js/globalUsage/jquery/jquery-3.2.0.min.js'))
    ;
//    echo $this->feedback()->startUp();
    ?>
</head>
<?php
    // set default values
    if (!isset($this->showSidebar)) {
        $this->showSidebar = true;
    }
    // usage in controller:
    //$this->layout()->setVariable('showSidebar', false);

    $fullWidth = ($this->showSidebar) ? '' : 'class="fullWidth"';
?>
<body>
    <div class="body box">
        <!----  NO SCRIPT   ---->
        <noscript>
            <div>
                <div>
                    <span class="ownhead">
                        Java Script aktivieren um diese Seite zu erleben!
                    </span>
                </div>
            </div>
        </noscript>
<!----  HEAD   ---->
        <div id="headcontainer">
             <div id="head">
                 <img class = "headdeko" src="/img/Wappenklein.png">
                 <div class = "leftHead">
                     <div class="head box">
                        <a class="ownhead" href="<?php echo $this->url('home') ?>">schwarze Ritter zu Augsburg</a>
                     </div>
                 </div>
                 <div class = "rightHead">
                     <a class="disclaim" href="#disclaim"> Haftungsausschluss</a><br class="js-L-view" />
                     <a href="#impress"> Impressum</a> <br class="js-L-view" />
                     <a href="#mail">Kontakt </a>
                 </div>
            </div>
            <div id="headlinks">
                <span class="own_text_big js-S-view hidden" style="text-align: left">
                    <?php $greet = $this->userinfo(); if ($greet != '') {echo $greet;} ?>
                </span>
            </div>
        </div>
<!----  NAVIGATION   ---->
        <div class="menu_button_div js-S-view hidden">
            <img class="menu_button_img" src="/img/uikit/menu_button.png">
        </div>
        <div id="navframe">
            <div class="menu_titel js-L-view hidden">
                <box class="navsign">
                    <span class="own_text_big">Wegweiser</span>
                </box>
            </div>
            <div class="overlayShadow menu_items js-L-view">
                <div class="topics">
                    <?php
                    echo $this->navigation('navigation')
                        ->menu()
                        ->setPartial('layout/menu.phtml')
                        ->renderPartial(); ?>
                </div>
            </div>
        </div>
<!----  CONTENT   ---->
    <!----  content   ---->
        <box id="content" <?php echo $fullWidth; ?> >
            <boxtitel>
                <span class="own_text_big">
                    <?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->renderStraight();//$this->contentTitle ?>
                </span>
                <br />
            </boxtitel>
            <boxcontent>
                <?php echo $this->content; ?>
            </boxcontent>
        </box>
        <?php if ($this->showSidebar): ?>
        <!----  rightbar   ---->
            <div id="rightcontainer">
        <?php endif; ?>
                <div class="rightbarup">
                    <?php echo $this->loginview(); ?>
                </div>
        <?php if ($this->showSidebar): ?>
                <box id="rightbarmiddle">
<!--                        --><?php //echo $this->randomImage()->scroller(); ?>
                </box>

                <box class="rightbardown">
                    <boxtitel>
                        <span class="own_text_medium">Termine</span><br>
                    </boxtitel>
                    <boxcontent>
                        under construction<br>comming soon
                        <!--- @todo kalender einbinden
                        <iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=sra_cal%40schwarze-ritter-augsburg.com&amp;color=%231B887A&amp;src=6h1fqs4om97fvrt8upgrgga1ds%40group.calendar.google.com&amp;color=%235F6B02&amp;src=j0g40fq5m45tt6i3ma30dle0fo%40group.calendar.google.com&amp;color=%232952A3&amp;ctz=Europe%2FBerlin"
                        style="border-width:1px; border-radius: 10px" width="95%" height="400" frameborder="0" scrolling="no">
                        </iframe>  --->
                    </boxcontent>
                </box>
             </div>
        <?php endif; ?>
        <div class="clear"></div>
<!----  FOOT   ---->
        <div id="foot">
            <div class="overlayShadow">
                <box id="foottext">
                    <ul>
                        <li>copyright © <v>F&S 2016</v> & Schwarze Ritter zu Augsburg | </li>
                        <li><a href="#mail">Kontakt</a> | </li>
                        <li><a href="#impress">Impressum</a> | </li>
                        <li><a class="disclaim" href="#disclaim">Haftungsausschluss</a> | </li>
                        <li><a href="http://www.schwert-und-mieder.de/">Schwert und Mieder e.V.</a></li>
                    </ul>
                </box>
            </div>
            <div style="height: 20px;"></div>
        </div>
        <?php echo $this->inlineScript() ?>
    </div>

    <link href="/css/jsOverrides.css" media="screen" rel="stylesheet" type="text/css">
</body>
</html>