<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Equipment\Module'                                          => __DIR__ . '/Module.php',
    'Equipment\Controller\EquipmentController'                  => __DIR__ . '/src/Equipment/Controller/EquipmentController.php',
    'Equipment\Controller\SitePlannerController'                => __DIR__ . '/src/Equipment/Controller/SitePlannerController.php',
    'Equipment\Factory\Controller\EquipmentControllerFactory'   => __DIR__ . '/src/Equipment/Factory/Controller/EquipmentControllerFactory.php',
    'Equipment\Factory\Controller\SitePlannerControllerFactory' => __DIR__ . '/src/Equipment/Factory/Controller/SitePlannerControllerFactory.php',
    'Equipment\Factory\Service\TentServiceFactory'              => __DIR__ . '/src/Equipment/Factory/Service/TentServiceFactory.php',
    'Equipment\Form\Filter\TentFilter'                          => __DIR__ . '/src/Equipment/Form/Filter/TentFilter.php',
    'Equipment\Form\TentForm'                                   => __DIR__ . '/src/Equipment/Form/TentForm.php',
    'Equipment\Model\EnumTentShape'                             => __DIR__ . '/src/Equipment/Model/EnumTentShape.php',
    'Equipment\Model\Tent'                                      => __DIR__ . '/src/Equipment/Model/Tent.php',
    'Equipment\Model\TentColorsTable'                           => __DIR__ . '/src/Equipment/Model/TentColorsTable.php',
    'Equipment\Model\TentSet'                                   => __DIR__ . '/src/Equipment/Model/TentSet.php',
    'Equipment\Model\TentTable'                                 => __DIR__ . '/src/Equipment/Model/TentTable.php',
    'Equipment\Model\TentTypesTable'                            => __DIR__ . '/src/Equipment/Model/TentTypesTable.php',
    'Equipment\Service\TentService'                             => __DIR__ . '/src/Equipment/Service/TentService.php',
);
