<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Equipment\Module'                               => __DIR__ . '/Module.php',
    'Equipment\Controller\EquipmentController'       => __DIR__ . '/src/Equipment/Controller/EquipmentController.php',
    'Equipment\Controller\SitePlannerController'     => __DIR__ . '/src/Equipment/Controller/SitePlannerController.php',
    'Equipment\Factory\SitePlannerControllerFactory' => __DIR__ . '/src/Equipment/Factory/SitePlannerControllerFactory.php',
    'Cast\Form\Filter\TentFilter'                    => __DIR__ . '/src/Equipment/Form/Filter/TentFilter.php',
    'Equipment\Model\EnumTentShape'                  => __DIR__ . '/src/Equipment/Model/EnumTentShape.php',
    'Equipment\Model\Tent'                           => __DIR__ . '/src/Equipment/Model/Tent.php',
    'Equipment\Model\TentColorsTable'                => __DIR__ . '/src/Equipment/Model/TentColorsTable.php',
    'Equipment\Model\TentSet'                        => __DIR__ . '/src/Equipment/Model/TentSet.php',
    'Equipment\Model\TentTable'                      => __DIR__ . '/src/Equipment/Model/TentTable.php',
    'Equipment\Model\TentTypesTable'                 => __DIR__ . '/src/Equipment/Model/TentTypesTable.php',
    'Equipment\Service\TentService'                  => __DIR__ . '/src/Equipment/Service/TentService.php',
);
