<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Album\Module'                           => __DIR__ . '/module.php',
    'Album\Controller\GalleryController'     => __DIR__ . '/src/Album/Controller/GalleryController.php',
    'Album\Factory\GalleryServiceFactory'    => __DIR__ . '/src/Album/Factory/GalleryServiceFactory.php',
    'Album\Factory\RandomImageHelperFactory' => __DIR__ . '/src/Album/Factory/RandomImageHelperFactory.php',
    'Album\Form\AlbumForm'                   => __DIR__ . '/src/Album/Form/AlbumForm.php',
    'Album\Form\ConfirmForm'                 => __DIR__ . '/src/Album/Form/ConfirmForm.php',
    'Album\Form\Filter\AlbumFilter'          => __DIR__ . '/src/Album/Form/Filter/AlbumFilter.php',
    'Album\Form\Filter\ImageFilter'          => __DIR__ . '/src/Album/Form/Filter/ImageFilter.php',
    'Album\Form\ImageForm'                   => __DIR__ . '/src/Album/Form/ImageForm.php',
    'Album\Model\AlbumModel'                 => __DIR__ . '/src/Album/Model/AlbumModel.php',
    'Album\Service\GalleryService'           => __DIR__ . '/src/Album/Service/GalleryService.php',
    'Album\Utility\RandomImageHelper'        => __DIR__ . '/src/Album/View/Helper/RandomImageHelper.php',
);
