<?php

$title = 'Delete Character';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete '<?php echo $this->escapeHtml($char['name'] . ' ' . $char['surename'] . "' von '" . $char['userName']); ?>' ?
 </p>
 <?php
 $url = $this->url('castmanager/characters/delete', array('id'=>$id));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>