<?php
$title = 'Families';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('families/add');?>">Add new Family</a>
 </p>

<?php
// $this->dataTable()->setJSOptions("");   das kannste dir ja sparen wenn der String leer ist, das ist er default
echo $this->dataTable()->render($families, array(
    'ID' => array(
        'type' => 'text',
        'key' => 'id'
    ),
    'test' => array(
        'type' => 'custom',
        'render' => function($dataRow) {
            return $dataRow['id'].':'.$dataRow['name'];
        },
    ),
                        'Name' => array(
                            'type' => 'text',
                            'key' => 'name'
                        ),
                        'Actions' => array(
                            'type' => 'custom',
                            'render' => function($dataRow) {
                                return '<a href="'.$dataRow['id'].'">Edit</a>';
                            },
                        ),
));
?>