<style>
 .image
 {
     height: 300px;
     position: absolute;
     left: 50%;
     top: 20%;
 }
</style>
<?php
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
     // === links
	 if (isset($links)){
		 foreach ($links as $key => $value): ?>
             <a href="<?php echo $value ?>">
                 <button><?php echo $key ?></button>
             </a>
		 <?php endforeach;
		 echo '<br/>';
		 echo '<br/>';
	 }

     if ($url !== null){
		 $form = $this->form;
		 $form->setAttribute('action', $url);
		 $form->prepare();
     }

 echo $this->form($form);

    $imageUrl = null;
    if (isset($image) || $image !== null) $imageUrl = $this->media()->getImageUrl($image);

    if ($imageUrl !== null): ?>
        <img class="image" src="<?php echo $imageUrl ?>" alt="image">

    <?php endif;?>

