<h1>Edit Content</h1>
<div id="page-edit">
<?php
// $this->headLink()->prependStylesheet('/js/jstree/themes/default-dark/style.css');
$this->headScript()->appendFile('/js/ckeditor/ckeditor.js');
$form = $this->form;
$form->setAttribute('action', $this->url('cms/edit', array(), true));
$form->prepare();
$form->get('submit')->setValue('Update');

echo $this->form($form);
?>
</div>
<script>
    $($('#page-edit textarea')[0]).attr("id","editor");
    CKEDITOR.replace( 'editor',{
        allowedContent: {
            script: true,
            div: true,
            $1: {
                // This will set the default set of elements
                elements: CKEDITOR.dtd,
                attributes: true,
                styles: true,
                classes: true
            }
        }
    });
</script>
