<?php
$title = 'Content List';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
dumpd($contentTable);
echo $this->dataTable()->render( $contentTable );
?>

<p>
    <a href="<?php echo $this->url('cms/add');?>">Add new Content</a>
</p>
<table class="table" style="width:90%">
    <tr>
        <th>Title</th>
        <th>Url</th>
        <th>&nbsp;</th>
    </tr>
 <?php foreach ($posts as $post) : ?>
     <tr>
         <td><?php echo $this->escapeHtml($post['title']);?></td>
         <td><?php echo $this->escapeHtml($post['url']);?></td>
         <td>
             <a href="<?php echo $this->url('cms/edit', array('id' => $post['id']));?>">Edit</a>
             <a href="<?php echo $this->url('cms/delete', array('id' => $post['id']));?>">Delete</a>
         </td>
     </tr>
 <?php endforeach; ?>
</table>
