<?php
$title = 'Wappen';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$this->dataTable()->render($blazons);

/** @var \Cast\View\BlazonHelper $bh */
$bh = $this->blazon();
$bh->setSize('big');
echo $bh->blazon(0, 'soldat', 2);
$bh->setSize('small');
echo $bh->blazon(0, null, 2);
$bh->setSize(75);
echo $bh->blazon(0, 'soldat');
$bh->setSize(50);
echo $bh->blazon(1);
?>