<box class="logging login loggedOut">
    <boxtitle>
        <span class="own_text_big js-L-view">Login</span>
        <button class="logoutbutton login-menu-toggle js-S-view" type="button">
            <div class="own_text_medium">Login</div>
        </button>
    </boxtitle>
    <boxcontent class="login-form">
        <?php

        $form = $this->form;
        $form->unFocus();
        $form->prepare();
        echo $this->form($form);

            if ($this->messages){
                echo '<ul>';
                foreach($this->messages as $message)
                {
                    echo '<li>'.$message.'</li>';
                }
                echo '</ul>';
            }
        ?>
        <br/>
        <a href="/register ">Registrieren</a> <br/><br/>
        <a href="/password/reset">Passwort vergessen?</a>
    </boxcontent>
</box>