<box class="rightbarup" style="margin-bottom: 0">
    <boxtitel>
        <span class="own_text_big">Login</span>
    </boxtitel>
    <boxcontent style="text-align: center">
        <?php
            $form = $this->form;
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();

            if ($this->messages){
                echo '<ul>';
                foreach($this->messages as $message)
                {
                    echo '<li>'.$message.'</li>';
                }
                echo '</ul>';
            }
        ?>
    </boxcontent>
</box>