<box class="logging logout">
    <boxtitel>
        <span class="own_text_small js-L-view"><?php $greet = $this->userinfo(); if ($greet != '') {echo $greet;} ?></span>
    </boxtitel>
    <boxcontent>
        <form method="get" action="/logout">
            <button class="logoutbutton" style="width:100%;" type="submit">
                <div class="own_text_medium" style="width:100%;">Logout</div>
            </button>
        </form>
        </boxcontent>
</box>