<?php

$title = 'Edit Permissions of "' . $roleName . '"';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div style="float: left">
    <?php
    $deleteForm->setAttribute('action', $this->url('permission/delete', array('id' => $roleID)));
    $deleteForm->prepare();
    echo $this->form($deleteForm);
    ?>
</div>
<div style="float: right">
<?php
$addForm->prepare();
$addForm->setAttribute('action', $this->url('permission/add'));
echo $this->form($addForm);
?>
</div>