<?php
$title = 'Edit Permissions for:';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1><br><br>
<?php
 foreach ($roles as $row => $role) {
     $roles[$row]['href'] = '<a href="' . $this->url('permission/edit', array('id' => $role['rid'])) . '">Ändern</a>';
 }
echo $this->dataTable()->render($roles, array (
    0 => array ( 'key' => 'role_name', 'headline' => 'Rolle'),
    1 => array ( 'key' => 'href', 'headline' => 'Aktion'),
));
?>