<style>
</style>
<?php echo $this->inlineFromFile('cast', 'cast', 'tree.css');  ?>
<?php
$this->headScript()->appendFile('/libs/jquery.workspace/jquery.workspace.js');
$this->headLink()->appendStylesheet('/libs/jquery.workspace/jquery.workspace.css');
bdump($root);
function createFamilyList($parent, $level) {
    echo '<li class="familyMember">';
    echo '<familymember name="'. $parent['name'] .'" data-id="'. $parent['id'] .'">';
    echo '<p>';
    echo '<span>'.$parent['name'].'</span> ';
    echo '<span>'.$parent['surename'].'</span>';
    echo '</p>';
    echo '<br>';
    echo '<p>';
    echo '<span>Family: </span>';
    echo '<span data-id="'. $parent['family_id'] .'">'.$parent['family_name'].'</span>';
    echo '</p>';
    echo '</familymember>';
    if (count($parent['dependent']) > 0) {
        echo '<ul>';
        if (count($parent['dependent']) > 0) {
            foreach ($parent['dependent'] as &$char) {
                createFamilyList($char, $level + 1);
            }
        }
        echo '</ul>';
    }
}
function createList($parent, $level) {
    echo '<li class="character">';
    echo '<character name="'. $parent['name'] .'" data-id="'. $parent['id'] .'">';
    echo '<p>';
    echo '<span>'.$parent['name'].'</span> ';
    echo '<span>'.$parent['surename'].'</span>';
    echo '</p>';
    echo '<br>';
    echo '<p>';
    echo '<span>Family: </span>';
    echo '<span data-id="'. $parent['family_id'] .'">'.$parent['family_name'].'</span>';
    echo '</p>';
    echo '</character>';

    if (isset($parent['family']) || count($parent['employ']) > 0) {
        echo '<ul>';
        if (isset($parent['family'])) {
            echo '<li class="family">';
            echo '<family name="' . $parent['name'] . '" data-id="' . $parent['id'] . '">';
            echo '<div class="details">';
            echo ' Family';
            echo '</div>';
            echo '<ul>';
            foreach ($parent['family']['members'] as &$member) {
            createFamilyList($member, $level + 1);
            }
            echo '</ul>';

            echo '</family>';
            echo '</li>';
        }
        if (count($parent['employ']) > 0) {
            foreach ($parent['employ'] as &$char) {
                createList($char, $level + 1);
            }
        }
        echo '</ul>';
    }
    echo '</li>';
}
?>

<box id="fullCastScroller">
    <boxtitel>
        <span class='own_text_small'>Staatshierarchie</span>
    </boxtitel>
    <boxcontent style="overflow: hidden; height: 500px;">

        <div class="tree" style="width: 2000px; height: 2000px;">
            <ul style="white-space:nowrap">
                <?php createList($root, 0); ?>
            </ul>

            <br style="clear:both"/>
        </div>

    </boxcontent>
</box>

<?php echo $this->inlineFromFile('cast', 'cast', 'scroller.js');  ?>
<!--<div class="cast">-->
<!--    <h1>Besetztung</h1>-->
<!--    --><?php //foreach ($this->chars as $char): ?>
<!--        <div class="box big">-->
<!--            <a href="/--><?php //echo $char['id']; ?><!--">-->
<!--                --><?php //echo $this->CharProfile()->small($char);?>
<!--            </a>-->
<!--            <br>-->
<!--            <p>Tross</p>-->
<!--            <ul class="tross">-->
<!--                --><?php //foreach($chars as $char): ?>
<!--                    <li>-->
<!--                        <a href="/--><?php //echo $char['id']; ?><!--">-->
<!--                            <div class="box small">-->
<!--                                --><?php //echo $this->CharProfile()->small($char); ?>
<!--                            </div>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                --><?php //endforeach; ?>
<!--            </ul>-->
<!--            <div style="clear: left"></div>-->
<!--        </div>-->
<!--    --><?php //endforeach ?>
<!---->
<!--</div>-->
