<style>
</style>
<?php echo $this->inlineFromFile('cast', 'cast', 'cast.css');  ?>
<?php
$this->headScript()->prependFile('/libs/jquery.workspace/jquery.workspace.js');
$this->headLink()->prependStylesheet('/libs/jquery.workspace/jquery.workspace.css');
$GLOBALS['bhelper'] = $this->blazon();

//cleanfix
bdump($root);

//function createReference($char){
//    $GLOBALS['parentBlazons'][$char['id']] = $char['blazon_id'];
//    if (isset($char['employ'])){
//        foreach ($char['employ'] as $employee){
//            createReference($employee);
//        }
//    }
//}
//createReference($root);

function createFamilyList($parent, $level) {
    echo '<li class="familyMember">';
    echo '<familymember name="'. $parent['name'] .'" data-id="'. $parent['id'] .'">';
    echo '<p>';
    echo '<span>'.$parent['name'].'</span> ';
    echo '<span>'.$parent['surename'].'</span>';
    echo '</p>';
    echo '<br>';
    echo '<p>';
    echo '<span>Family: </span>';
    echo '<span data-id="'. $parent['family_id'] .'">'.$parent['family_name'].'</span>';
    echo '</p>';
    echo linkCreator($parent);
    echo '</familymember>';
    if (count($parent['dependent']) > 0) {
        echo '<ul>';
        if (count($parent['dependent']) > 0) {
            foreach ($parent['dependent'] as &$char) {
                createFamilyList($char, $level + 1);
            }
        }
        echo '</ul>';
    }
}
function createList($parent, $level) {
    /** @var \Cast\View\Helper\BlazonHelper $bh */
    $bh = $GLOBALS['bhelper'];
    $blazonArguments = $bh->getBlazonHelperArgumentsByCharacter($parent);
    echo '<li class="character">';
    echo '<character name="'. $parent['name'] .'" data-id="'. $parent['id'] .'" class="box">';
    echo '<p>';
    echo '<span>'.$parent['name'].'</span> ';
    echo '<span>'.$parent['surename'].'</span>';
    echo '</p>';
    echo '<br>';
    echo $bh->blazon($blazonArguments);
    echo '<br>';
    echo '<p>'. $parent['job_name'] .'</p>';
    echo '<p>';
    if ($parent['surename'] !== $parent['family_name']) {
        if ($parent['family_id'] !== null) {
            echo '<span>Family: </span>';
            echo '<span data-id="' . $parent['family_id'] . '">' . $parent['family_name'] . '</span>';
        }
    }
    echo '</p>';
    echo linkCreator($parent);
    echo '</character>';

    if (isset($parent['family']) || count($parent['employ']) > 0) {
        $blazonArguments = $bh->getBlazonHelperArgumentsByCharacter($parent);//hä
        echo '<ul>';
        if (isset($parent['family'])) {
            echo '<li class="family">';
            echo '<family name="' . $parent['name'] . '" data-id="' . $parent['id'] . '">';
            echo '<br>';
            //Todo family blazon
            echo $bh->getSingleBlazon($blazonArguments, 'big');
            echo '<br>';
            echo '<div class="details">';
            echo $parent['family']['name'];
            echo '</div>';
            echo '<ul>';
            foreach ($parent['family']['members'] as &$member) {
                createFamilyList($member, $level + 1);
            }
            echo '</ul>';

            echo '</family>';
            echo '</li>';
        }
        if (count($parent['employ']) > 0) {
            foreach ($parent['employ'] as &$char) {
                createList($char, $level + 1);
            }
        }
        echo '</ul>';
    }
    echo '</li>';
}
function linkCreator($parent){
    $profileRoot = 'profile/' . $parent['userName'];
    $castProfile = $profileRoot . '/' . $parent['charURL'];

    $link1 = '<br/><div class="onlyCentered">';
    $link1 .= '<a href="' . $castProfile . '">Darstellung</a>';
    $link1 .= '</div>';

    $link2 = '<div class="onlyCentered">';
    $link2 .= '<a href="' . $profileRoot . '">Darsteller</a>';
    $link2 .= '</div><br/>';
    return $link1 . $link2;
}
?>

<box id="fullCastScroller">
    <boxtitle>
        <span class='own_text_small'>Staatshierarchie</span>
    </boxtitle>
    <boxcontent>

        <div class="tree" style="width: 2000px; height: 2000px; display:none">
            <ul style="white-space:nowrap">
                <?php
                createList($root, 0); ?>
            </ul>

            <br style="clear:both"/>
        </div>

    </boxcontent>
</box>

<?php echo $this->inlineFromFile('cast', 'cast', 'scroller.js');  ?>