<div class="cast">
    <h1>Besetztung</h1>
    <?php foreach ($this->chars as $char): ?>
        <div class="box big">
            <a href="/<?php echo $char['id']; ?>">
                <?php echo $this->CharProfile()->small($char);?>
            </a>
            <br>
            <p>Tross</p>
            <ul class="tross">
                <?php foreach($chars as $char): ?>
                    <li>
                        <a href="/<?php echo $char['id']; ?>">
                            <div class="box small">
                                <?php echo $this->CharProfile()->small($char); ?>
                            </div>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <div style="clear: left"></div>
        </div>
    <?php endforeach ?>

</div>
