<?php
$title = 'Cast Manager';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1><br>
 <?php foreach ($items as $item):

     $count = $item.'Count';?>
     <a href="<?php echo $this->url('castmanager/'.$item);?>">
         <box class= "castmanager">
                <div class="titel linkbox">
                    <p class="castManagerTitel">
                        <?php echo ucfirst($item);?>
                    </p>
                </div>
            <boxcontent>
                <p>Entrys: <?php echo $$count;?></p>
            </boxcontent>
        </box>
     </a>
 <?php endforeach; ?>
<div class="clear" style="height: 10px"></div>

